services:
        mariadb:
                container_name: mariadb
                build: requirements/mariadb
                image: mariadb
                environment:
                        MYSQL_USERNAME: ${MYSQL_USERNAME}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                        MYSQL_PASSWORD_ROOT: ${MYSQL_PASSWORD_ROOT}
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - inception
                healthcheck:
                        test: ["CMD-SHELL", "mysqladmin ping -uroot -p${MYSQL_PASSWORD_ROOT}"]
                        interval: 3s
                        timeout: 3s
                        retries: 10
                restart: unless-stopped
        wordpress:
                container_name: wordpress
                build: requirements/wordpress
                image: wordpress
                environment:
                        WORDPRESS_DB_HOST: mariadb:3306
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
                        WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
                        WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
                        WORDPRESS_USERNAME_OP: ${WORDPRESS_USERNAME_OP}
                        WORDPRESS_PASSWORD_OP: ${WORDPRESS_PASSWORD_OP}
                        WORDPRESS_EMAIL_OP: ${WORDPRESS_EMAIL_OP}
                        MYSQL_USERNAME: ${MYSQL_USERNAME}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                        MYSQL_PASSWORD_ROOT: ${MYSQL_PASSWORD_ROOT}
                        DOMAIN_NAME: ${DOMAIN_NAME}
                        TITLE: ${TITLE}
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - inception
                depends_on:
                        mariadb:
                                condition: service_healthy
                healthcheck:
                        test: ["CMD-SHELL", "cgi-fcgi -bind -connect wordpress:9000"]
                        interval: 3s
                        timeout: 3s
                        retries: 10
                restart: unless-stopped
        nginx:
                container_name: nginx
                build: requirements/nginx
                image: nginx
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - inception
                ports:
                        - "443:443"
                depends_on:
                        mariadb:
                                condition: service_healthy
                        wordpress:
                                condition: service_healthy
                restart: unless-stopped

volumes:
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/ttrave/data/mariadb
                        type: none
                        o: bind
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/ttrave/data/wordpress
                        type: none
                        o : bind

networks:
        inception:
                name: inception
                driver: bridge
